### ISSUE TITLE
Only accepted people can use a pgrok server

### ISSUE THREAD

**Issue by NhProGamer** [jerson/pgrok#21]
Is it possible to make sure that only accepted people can use my pgrok server?

**Comment by jerson** [comment]
HI @NhProGamer yes you can use a CA and a client certificate per person, all client certificate needs to be generated by that CA in order to validate that connection

https://github.com/jerson/pgrok/blob/master/docs/SELFHOSTING.md#protect-you-clientpgrok-to-serverpgrokd-connection-with-a-ca

is not a very convenient solution but you can algo generate one client certificate for all you allowed clients

https://campus.barracuda.com/product/webapplicationfirewall/doc/12193120/creating-a-client-certificate/

**Comment by NhProGamer** [comment]
Oh okay, thanks you so much

**Comment by NhProGamer** [comment]
It's that possible to build pgrok with these certs ?
